# Local
defaults:
    - scope:
          path: ""
      values:
          layout: "default"
          toc: true
plugins:
    - jekyll-toc

# Local + GitHub
markdown: kramdown
toc:
    list_id: tableOfContents
    list_class: toc--list
    sublist_class: toc--sub-list
    item_class: toc--entry
    item_prefix: toc--
kramdown:
    syntax_highlighter_opts:
        disable: true
titles_from_headings:
    enabled: true
    strip_title: false
